name: Deploy to IONOS

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 6

    - name: Install dependencies
      run: sudo apt update && sudo apt-get install git-ftp -y

    - name: Deploy via Git-FTP
      env:
        URL: ${{ secrets.FTP_SERVER }}
        USER: ${{ secrets.FTP_USER }}
        PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: git ftp push -v --auto-init --insecure -u $USER -p $PASSWORD $URL