name: Deploy to IONOS

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    env: 
      FTP_USER: ${{ secrets.FTP_USER }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      URL: ${{ secrets.FTP_SERVER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 6

      - name: Install dependencies
        run: sudo apt update && sudo apt-get install git-ftp -y

      - name: Force Upload ALL files
        run: git ftp init --insecure -u "$FTP_USER" -p "$FTP_PASSWORD" "$URL"
